### PR TITLE
include __init__ files in version specific of_core utils modules

### PR DESCRIPTION
**Pull request by erickvermot**
Based on the problem reported in the email:

File "/var/lib/kytos/napps/kytos/of_core/main.py", line 23, in <module>
    import napps.kytos.of_core.v0x01.utils as of_core_v0x01_utils
ModuleNotFoundError: No module named 'napps.kytos.of_core.v0x01'

somehow it relates to this: https://www.python.org/dev/peps/pep-0420/

### CODE REVIEW

**Comment by renanrodrigo** [comment]
But PEP420 says, in "Specification"
" Regular packages will continue to have an __init__.py and will reside in a single directory.
Namespace packages cannot contain an __init__.py "

and:
(...)
"While looking for a module or package named "foo", for each directory in the parent path:
-    If <directory>/foo/__init__.py is found, a regular package is imported and returned.
-    If not, but <directory>/foo.{py,pyc,so,pyd} is found, a module is imported and returned. "

AFAIK, the inclusion of __init__ in the modules would theoretically turn them into packages. How does it affect the imports overall?

**Comment by erickvermot** [comment]
@renanrodrigo for it to be imported as a simple module, it would neet to be in the same parent directory. 

Without the __init__.py, the v0x01 folder ends up becomming a namespace package, which is not what we want...

```
 During import processing, the import machinery will continue to iterate over each directory in the parent path as it does in Python 3.2. While looking for a module or package named "foo", for each directory in the parent path:

    If <directory>/foo/__init__.py is found, a regular package is imported and returned.
    If not, but <directory>/foo.{py,pyc,so,pyd} is found, a module is imported and returned. The exact list of extension varies by platform and whether the -O flag is specified. The list here is representative.
    If not, but <directory>/foo is found and is a directory, it is recorded and the scan continues with the next directory in the parent path.
    Otherwise the scan continues with the next directory in the parent path.

If the scan completes without returning a module or package, and at least one directory was recorded, then a namespace package is created. The new namespace package:

    Has a __path__ attribute set to an iterable of the path strings that were found and recorded during the scan.
    Does not have a __file__ attribute.

Note that if "import foo" is executed and "foo" is found as a namespace package (using the above rules), then "foo" is immediately created as a package. The creation of the namespace package is not deferred until a sub-level import occurs. 
```

**Comment by erickvermot** [comment]
I believe the reason why it worked for us without the ``__init__`` but it didn't in the case mentioned in the email may be related to some fixes related the the ``path`` and ``import`` machinery that were introduced in python 3.6.1.
If the user was runing python 3.6, then it could be related to this, but I'm not sure.

from the changelog:
    https://docs.python.org/3/whatsnew/changelog.html

    > bpo-29723: The sys.path[0] initialization change for bpo-29139 caused a regression by revealing an inconsistency in how sys.path is initialized when executing __main__ from a zipfile, directory, or other import location. The interpreter now consistently avoids ever adding the import location’s parent directory to sys.path, and ensures no other sys.path entries are inadvertently modified when inserting the import location named on the command line.

**Comment by beraldoleal** [comment]
I will accept this PR, but I think that we should create another PR like this for RC branch.

**Comment by diraol** [comment]
@beraldoleal there is no tags/branches on this repository. =)

**Comment by beraldoleal** [comment]
@diraol you are right hehehhe thanks.

**Pull request merged**
